export const POST_LISTING_REQUEST = 'POST/LISTING/REQUEST';
export const POST_LISTING_SUCCESS = 'POST/LISTING/SUCCESS';
export const POST_LISTING_FAILED = 'POST/LISTING/FAILED';

export const POST_CREATE_REQUEST = 'POST/CREATE/REQUEST';
export const POST_CREATE_SUCCESS = 'POST/CREATE/SUCCESS';
export const POST_CREATE_FAILED = 'POST/CREATE/FAILED';

export const POST_UPDATE_REQUEST = 'POST/UPDATE/REQUEST';
export const POST_UPDATE_SUCCESS = 'POST/UPDATE/SUCCESS';
export const POST_UPDATE_FAILED = 'POST/UPDATE/FAILED';

export const POST_DELETE_REQUEST = 'POST/DELETE/REQUEST';
export const POST_DELETE_SUCCESS = 'POST/DELETE/SUCCESS';
export const POST_DELETE_FAILED = 'POST/DELETE/FAILED';
