export const FILM_LISTING_REQUEST = 'FILM/LISTING/REQUEST';
export const FILM_LISTING_SUCCESS = 'FILM/LISTING/SUCCESS';
export const FILM_LISTING_FAILED = 'FILM/LISTING/FAILED';

export const FILM_CREATE_REQUEST = 'FILM/CREATE/REQUEST';
export const FILM_CREATE_SUCCESS = 'FILM/CREATE/SUCCESS';
export const FILM_CREATE_FAILED = 'FILM/CREATE/FAILED';

export const FILM_UPDATE_REQUEST = 'FILM/UPDATE/REQUEST';
export const FILM_UPDATE_SUCCESS = 'FILM/UPDATE/SUCCESS';
export const FILM_UPDATE_FAILED = 'FILM/UPDATE/FAILED';

export const FILM_DELETE_REQUEST = 'FILM/DELETE/REQUEST';
export const FILM_DELETE_SUCCESS = 'FILM/DELETE/SUCCESS';
export const FILM_DELETE_FAILED = 'FILM/DELETE/FAILED';
